### ISSUE TITLE
Move SublimeText snippets in different Project

### ISSUE THREAD

**Issue by varemenos** [newaeonweb/responsiveboilerplate#1]
There is pretty much no point in keeping your boilerplate and the snippets in the same repository.
The boilerplate should be a starting point for the developer, deleting the snippet folder ever time the developer creates a new project is kinda missing the point of a boilerplate.

Linking the ST snippet's repository to the description should be good enough for the newcomers to notice...

**Comment by newaeonweb** [comment]
Hello, thanx for the tip.
i'm working on it.

**Comment by newaeonweb** [comment]
Ok, Major update today, Also was created a separate snippets folder with more features.
