### ISSUE TITLE
Less fails to compile responsiveboilerplate.less

### ISSUE THREAD

**Issue by fterenzani** [newaeonweb/responsiveboilerplate#13]
When I try to compile boilerplate.less with the Koala GUI I get the error bellow:

C:\Users\xxx\Desktop\layout\responsiveboilerplate-2.3.4\less\responsiveboilerplate.less
ParseError: Unrecognised input in C:\Users\xxx\Desktop\layout\responsiveboilerplate-2.3.4\less\gridcolumns.less:44:1
43  //Fluid Engine Generator
44  .fluidRbgrid (@RbfluidgridColumnWidth, @RbfluidgridGutterWidth) {
45 

I get similar errors with other GUI for Windows

**Comment by newaeonweb** [comment]
Hello @fterenzani will try to simulate the erro.
