### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by gazhay** [newaeonweb/responsiveboilerplate#3]
Just downloaded from the website,

Followed the instructions, I just get a "reset" html page with any content showing as times font left aligned.

I even copied the html from the example page and inserted that, same result. No columns, just left aligned text with a small margin.

Checked permissions, tried locally, and on a server.

**Comment by newaeonweb** [comment]
Hello Gazay, sorry for my delay. Very strange i download the zip folder now and made a simple test and work Perfect.
The index.html file have a block of code commented, just uncomment and place some code or words between the tags.
I'll put another example on the index file to make a better first look with the tool.
